---
title: "PlotExample"
author: "Win-Vector LLC"
date: "12/21/2017"
output: github_document
---

```{r setup}
library("ggplot2")
library("cdata")
library("seplyr")
library("keras")
library("kableExtra")
options(knitr.table.format = "html") 

h <- readRDS("historyobject.rds")
plot(h)

d <- readRDS("metricsframe.rds")
d$epoch <- seq_len(nrow(d))
d$loss <- -d$loss
d$val_loss <- -d$val_loss
knitr::kable(head(d))
```

```{r firstplot}
cT <- buildUnPivotControlTable(
  nameForNewKeyColumn= 'origColName',
  nameForNewValueColumn= 'performance',
  columnsToTakeFrom= c('val_loss',
                       'val_acc',
                       'loss',
                       'acc' ))
dT <- moveValuesToRowsD(
  d,
  controlTable = cT,
  columnsToCopy = "epoch")
knitr::kable(head(dT))

mp <- data.frame(
  origColName = qc(val_loss, val_acc, 
                     loss, acc),
  dataset = qc("validation", "validation", 
               "training", "training"),
  measure = qc("- binary cross entropy", "accuracy",
               "- binary cross entropy", "accuracy"),
  stringsAsFactors = FALSE)
knitr::kable(mp)


dT <- map_fieldsD(dT, 
                  "origColName",
                  mp)
dT$measure <- factor(dT$measure, 
                     levels = c("- binary cross entropy",
                                "accuracy"))
knitr::kable(head(dT))

pick <- dT %.>%
  filter_se(.,
            qe(measure == "- binary cross entropy",
               dataset == "validation")) %.>%
  .$epoch[[which.max(.$performance)]]

ggplot(data = dT, 
       aes(x = epoch, 
           y = performance,
           color = dataset)) +
  geom_point() +
  stat_smooth(geom = "line", se = FALSE, method = "loess", alpha = 0.5) +
  facet_wrap(~measure, ncol=1, scales = "free_y") +
  geom_vline(xintercept = pick, alpha=0.7, color='darkgreen') +
  scale_color_brewer(palette = "Dark2") + 
  ggtitle("model performance by epoch, dataset, and measure")
```


```{r lineplot}
d %.>%
  head(., n=1) %.>%
  select_se(., qc(val_loss, val_acc, loss, acc)) %.>%
  knitr::kable(.)  %.>%
  kable_styling(., full_width = F) %.>%
  column_spec(., 1:4, background = "yellow")

cT <- dplyr::tribble(
  ~measure,                 ~training, ~validation,
  "- binary cross entropy", "loss",    "val_loss",
  "accuracy",               "acc",     "val_acc"
)
cT %.>%
  knitr::kable(.) %.>%
  kable_styling(., full_width = F) %.>%
  column_spec(., c(2,3), background = "yellow")


d %.>%
  head(., n=1) %.>%
  moveValuesToRowsD(
    .,
    controlTable = cT) %.>%
  knitr::kable(.) %.>%
  kable_styling(., full_width = F) %.>%
  column_spec(., c(2,3), background = "yellow")

dT <- moveValuesToRowsD(
  d,
  controlTable = cT,
  columnsToCopy = "epoch")

dT$measure <- factor(dT$measure, 
                     levels = c("- binary cross entropy",
                                "accuracy"))
knitr::kable(head(dT))

# note: this step requres wrapr 1.0.3 or better
dT <- dT %.>%
  mutate_se(.,
            qae(rmin := ifelse(validation <= training, validation, NA),
                rmax := ifelse(validation <= training, training, NA),
                discounted := ifelse(validation <= training, 
                                     validation - 0.1*(training-validation), 
                                     validation)))

pick <- dT %.>%
  filter_se(.,
            qe(measure == "- binary cross entropy")) %.>%
  .$epoch[[which.max(.$discounted)]]



ggplot(data = dT, 
       aes(x = epoch,
           xend = epoch,
           y = validation,
           yend = training,
           ymin = rmin,
           ymax = rmax)) +
  geom_segment() +
  geom_point() +
  geom_point(aes(y = training), shape = 3) +
  stat_smooth(geom = "line",
              se = FALSE, 
              color  = "#d95f02", 
              alpha = 0.8,
              method = "loess") +
  stat_smooth(geom = "line",
              aes(y = discounted),
              se = FALSE, 
              color  = "#d95f02", 
              alpha = 0.2,
              method = "loess",
              linetype = 2) +
  geom_ribbon(alpha=0.2, fill = "#1b9e77") +
  geom_vline(xintercept = pick, alpha=0.7, color='#e6ab02') +
  facet_wrap(~measure, ncol=1, scales = 'free_y') +
  ylab("performance") +
  ggtitle("plotting over-fit as a function of epoch")
```
